# Generated by Django 5.0.1 on 2024-01-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16, verbose_name="title")),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=11, verbose_name="phone number"),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "level 1"),
                            (2, "level 2"),
                            (3, "level 3"),
                            (4, "level 4"),
                        ],
                        default=1,
                        verbose_name="level",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Used"), (2, "Not used")],
                        default=2,
                        verbose_name="status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="username")),
                ("password", models.CharField(max_length=64, verbose_name="password")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="age")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (2, "Female")], verbose_name="gender"
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.department",
                        verbose_name="department",
                    ),
                ),
            ],
        ),
    ]
